"""``read``/``find --scope`` resolve a relative path like ``grep`` would:

absolute as given; else relative to the invoking cwd if that exists inside
the project root; else relative to the project root. A path that resolves
outside the root is refused. Exercised through the real launcher
(``scripts/docmesh``) with ``--deterministic`` so no model download is
required.
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[4]
DOCMESH = ROOT / "plugins" / "docmesh" / "scripts" / "docmesh"

_MANIFEST = """# Generated by docmesh init; paths are relative to this project when possible.
version = 1
model = "BAAI/bge-small-en-v1.5"
tokenizer = "fastembed"
max_embedding_tokens = 400
hard_embedding_tokens = 480
breadcrumb_format = " > "
retrieval_prefix = ""
chunking_version = "v1-recursive-lines-paragraphs-token-count-probe"
include = ["**/*.md", "**/*.mdx", "**/*.tex", "**/*.latex", "**/*.bib", "**/*.txt", "**/*.text", "**/*.pdf"]
exclude = [".git/**", ".docmesh/**", ".venv/**", "venv/**", "node_modules/**", "build/**", "dist/**"]
"""


def _run(args: list[str], cwd: Path) -> dict:
    result = subprocess.run(
        [str(DOCMESH), *args, "--deterministic", "--json"],
        cwd=cwd,
        env={**os.environ, "DOCMESH_NO_NETWORK": "1"},
        text=True,
        capture_output=True,
        check=False,
    )
    assert result.stdout.strip(), result.stderr
    return json.loads(result.stdout.strip().splitlines()[-1])


class CwdRelativePathTests(unittest.TestCase):
    def _project(self, directory: str) -> Path:
        project = Path(directory) / "project"
        (project / ".docmesh").mkdir(parents=True)
        (project / ".docmesh" / "manifest.toml").write_text(
            _MANIFEST, encoding="utf-8"
        )
        (project / "paper").mkdir()
        (project / "paper" / "notes.md").write_text(
            "# Notes\nneedle here.\n", encoding="utf-8"
        )
        subprocess.run(
            [str(DOCMESH), "index", "--project-root", str(project), "--deterministic"],
            cwd=project,
            env={**os.environ, "DOCMESH_NO_NETWORK": "1"},
            text=True,
            capture_output=True,
            check=True,
        )
        return project

    def test_cwd_relative_read_works_from_a_parent_directory(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            project = self._project(directory)
            payload = _run(
                [
                    "read",
                    "--root",
                    str(project),
                    "--path",
                    "project/paper/notes.md",
                ],
                cwd=Path(directory),
            )
            self.assertIn("needle", payload["content"])

    def test_root_relative_read_still_works(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            project = self._project(directory)
            payload = _run(
                [
                    "read",
                    "--root",
                    str(project),
                    "--path",
                    "paper/notes.md",
                ],
                cwd=project,
            )
            self.assertIn("needle", payload["content"])

    def test_path_outside_root_is_refused(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            project = self._project(directory)
            outside = Path(directory) / "outside.md"
            outside.write_text("not part of the project", encoding="utf-8")
            payload = _run(
                [
                    "read",
                    "--root",
                    str(project),
                    "--path",
                    "../outside.md",
                ],
                cwd=project,
            )
            self.assertFalse(payload.get("ok", True), payload)
            self.assertIn("outside the project root", str(payload.get("error", "")))


if __name__ == "__main__":
    unittest.main()
